# Import necessary libraries

In [2]:
from pycaret.classification import *
import pandas as pd

# Load your CSV file

In [3]:
 file_path = './datasets/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
df = pd.read_csv('Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv')

In [4]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df.shape

(74684, 79)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74684 entries, 0 to 74683
Data columns (total 79 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0    Destination Port             74684 non-null  int64
 1    Flow Duration                74684 non-null  int64
 2    Total Fwd Packets            74684 non-null  int64
 3    Total Backward Packets       74684 non-null  int64
 4   Total Length of Fwd Packets   74684 non-null  int64
 5    Total Length of Bwd Packets  74684 non-null  int64
 6    Fwd Packet Length Max        74684 non-null  int64
 7    Fwd Packet Length Min        74684 non-null  int64
 8    Fwd Packet Length Mean       74684 non-null  float64
 9    Fwd Packet Length Std        74684 non-null  float64
 10  Bwd Packet Length Max         74684 non-null  int64
 11   Bwd Packet Length Min        74684 non-null  int64
 12   Bwd Packet Length Mean       74684 non-null  float64
 13   Bwd Packet Length Std        74684 non-null  float64
 14  Flow Bytes/s                  74681 non-null  float64
 15   Flow Packets/s               74684 non-null  float64
 16   Flow IAT Mean                74684 non-null  float64
 17   Flow IAT Std                 74684 non-null  float64
 18   Flow IAT Max                 74683 non-null  float64
 19   Flow IAT Min                 74683 non-null  float64
 20  Fwd IAT Total                 74683 non-null  float64
 21   Fwd IAT Mean                 74683 non-null  float64
 22   Fwd IAT Std                  74683 non-null  float64
 23   Fwd IAT Max                  74683 non-null  float64
 24   Fwd IAT Min                  74683 non-null  float64
 25  Bwd IAT Total                 74683 non-null  float64
 26   Bwd IAT Mean                 74683 non-null  float64
 27   Bwd IAT Std                  74683 non-null  float64
 28   Bwd IAT Max                  74683 non-null  float64
 29   Bwd IAT Min                  74683 non-null  float64
 30  Fwd PSH Flags                 74683 non-null  float64
 31   Bwd PSH Flags                74683 non-null  float64
 32   Fwd URG Flags                74683 non-null  float64
 33   Bwd URG Flags                74683 non-null  float64
 34   Fwd Header Length            74683 non-null  float64
 35   Bwd Header Length            74683 non-null  float64
 36  Fwd Packets/s                 74683 non-null  float64
 37   Bwd Packets/s                74683 non-null  float64
 38   Min Packet Length            74683 non-null  float64
 39   Max Packet Length            74683 non-null  float64
 40   Packet Length Mean           74683 non-null  float64
 41   Packet Length Std            74683 non-null  float64
 42   Packet Length Variance       74683 non-null  float64
 43  FIN Flag Count                74683 non-null  float64
 44   SYN Flag Count               74683 non-null  float64
 45   RST Flag Count               74683 non-null  float64
 46   PSH Flag Count               74683 non-null  float64
 47   ACK Flag Count               74683 non-null  float64
 48   URG Flag Count               74683 non-null  float64
 49   CWE Flag Count               74683 non-null  float64
 50   ECE Flag Count               74683 non-null  float64
 51   Down/Up Ratio                74683 non-null  float64
 52   Average Packet Size          74683 non-null  float64
 53   Avg Fwd Segment Size         74683 non-null  float64
 54   Avg Bwd Segment Size         74683 non-null  float64
 55   Fwd Header Length.1          74683 non-null  float64
 56  Fwd Avg Bytes/Bulk            74683 non-null  float64
 57   Fwd Avg Packets/Bulk         74683 non-null  float64
 58   Fwd Avg Bulk Rate            74683 non-null  float64
 59   Bwd Avg Bytes/Bulk           74683 non-null  float64
 60   Bwd Avg Packets/Bulk         74683 non-null  float64
 61  Bwd Avg Bulk Rate             74683 non-null  float64
 62  Subflow Fwd Packets           74683 non-null  float64
 63   Subflow Fwd Bytes            74683 non-null  float64
 64   Subflow Bwd Packets          74683 non-null  float64
 65   Subflow Bwd Bytes            74683 non-null  float64
 66  Init_Win_bytes_forward        74683 non-null  float64
 67   Init_Win_bytes_backward      74683 non-null  float64
 68   act_data_pkt_fwd             74683 non-null  float64
 69   min_seg_size_forward         74683 non-null  float64
 70  Active Mean                   74683 non-null  float64
 71   Active Std                   74683 non-null  float64
 72   Active Max                   74683 non-null  float64
 73   Active Min                   74683 non-null  float64
 74  Idle Mean                     74683 non-null  float64
 75   Idle Std                     74683 non-null  float64
 76   Idle Max                     74683 non-null  float64
 77   Idle Min                     74683 non-null  float64
 78   Label                        74683 non-null  float64
dtypes: float64(69), int64(10)
memory usage: 45.0 MB

# Drop missing data

In [7]:
dfr = df.dropna()

## Finding percentage of missing observations per variable after dropping

In [8]:
def missing_data(df):
    total = df.isnull().sum().sort_values(ascending = False)
    percent = (df.isnull().sum()/df.isnull().count()*100).sort_values(ascending = False)
    return pd.concat([total, percent], axis=1, keys=['Total NaN Values', 'Percentage of NaN Values'])

missing_data(df)

                        Total NaN Values  Percentage of NaN Values
Flow Bytes/s                           3                  0.004017
 Max Packet Length                     1                  0.001339
 Bwd Avg Bytes/Bulk                    1                  0.001339
 Fwd Avg Packets/Bulk                  1                  0.001339
Fwd Avg Bytes/Bulk                     1                  0.001339
...                                  ...                       ...
 Bwd Packet Length Std                 0                  0.000000
 Flow Packets/s                        0                  0.000000
 Flow IAT Mean                         0                  0.000000
 Flow IAT Std                          0                  0.000000
 Destination Port                      0                  0.000000

[79 rows x 2 columns]

## Identify and  remove the rows of missing data from the above dataset

In [9]:
df = df.dropna(thresh=15)
df = df.dropna(subset=['Flow Bytes/s'])

## Finding percentage of missing observations per variable after dropping

In [10]:
def missing_data(df):
    total = df.isnull().sum().sort_values(ascending = False)
    percent = (df.isnull().sum()/df.isnull().count()*100).sort_values(ascending = False)
    return pd.concat([total, percent], axis=1, keys=['Total NaN Values', 'Percentage of NaN Values'])

missing_data(df)

                       Total NaN Values  Percentage of NaN Values
 Max Packet Length                    1                  0.001339
 ECE Flag Count                       1                  0.001339
 Fwd Avg Packets/Bulk                 1                  0.001339
Fwd Avg Bytes/Bulk                    1                  0.001339
 Fwd Header Length.1                  1                  0.001339
...                                 ...                       ...
Flow Bytes/s                          0                  0.000000
 Flow Packets/s                       0                  0.000000
 Flow IAT Mean                        0                  0.000000
 Flow IAT Std                         0                  0.000000
 Destination Port                     0                  0.000000

[79 rows x 2 columns]

In [11]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
count,74681.000000,7.468100e+04,74681.000000,74681.000000,74681.000000,7.468100e+04,74681.000000,74681.000000,74681.000000,74681.000000,...,74680.000000,7.468000e+04,7.468000e+04,7.468000e+04,7.468000e+04,7.468000e+04,7.468000e+04,7.468000e+04,7.468000e+04,74680.000000
mean,6597.374325,1.421795e+07,5.059747,4.977893,703.230420,6.592937e+03,362.204108,24.949411,115.551118,139.931393,...,21.946385,1.635669e+05,1.837794e+04,1.965513e+05,1.531344e+05,8.532448e+06,2.808348e+06,1.052122e+07,6.532085e+06,0.550241
std,16935.553055,2.831261e+07,15.929285,22.452026,3180.113731,3.982342e+04,1468.258881,146.193519,412.155081,627.642100,...,4.699975,8.460616e+05,2.888970e+05,1.008895e+06,8.215732e+05,1.848477e+07,1.026649e+07,2.252584e+07,1.678040e+07,0.497473
min,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,80.000000,5.149500e+04,2.000000,1.000000,26.000000,0.000000e+00,6.000000,0.000000,6.000000,0.000000,...,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,80.000000,1.108842e+06,3.000000,4.000000,30.000000,2.040000e+02,20.000000,0.000000,8.666667,3.464102,...,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,80.000000,8.013660e+06,5.000000,6.000000,64.000000,1.160100e+04,35.000000,6.000000,33.000000,10.263203,...,20.000000,1.014000e+03,0.000000e+00,1.014000e+03,1.013000e+03,7.902796e+06,0.000000e+00,7.912812e+06,6.733140e+06,1.000000
max,61538.000000,1.199994e+08,1681.000000,2942.000000,120783.000000,4.991419e+06,11680.000000,1472.000000,3867.000000,6692.644993,...,52.000000,1.000000e+08,3.950000e+07,1.000000e+08,1.000000e+08,1.200000e+08,6.530000e+07,1.200000e+08,1.200000e+08,1.000000

# Visualise Data

In [12]:
from IPython import display
from ipywidgets import widgets
import matplotlib.pyplot as plt
import seaborn as sns

## Display all column names

In [13]:
# Load your CSV file
file_path = 'Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
df = pd.read_csv(file_path)

# Display all column names
column_names = df.columns.tolist()
print("Column names:", column_names)

Column names: [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', ' Label']

<hr>

# Remove Missing Values

In [14]:
# Replace 'Label' with the actual name of your target variable
label_column = ' Label'

In [15]:
if label_column in df.columns:
    print(f"{label_column} is present in the DataFrame.")
else:
    print(f"{label_column} is not present in the DataFrame.")

 Label is present in the DataFrame.

## Check for missing values in the Label column

In [16]:
missing_values = df[label_column].isnull().sum()

print(f"Number of missing values in {label_column} column: {missing_values}")

Number of missing values in  Label column: 1

## Remove rows with missing values in the Label column

In [17]:
df = df.dropna(subset=[label_column])

# Verify that missing values have been removed
missing_values_after_removal = df[label_column].isnull().sum()

print(f"Number of missing values in {label_column} column after removal: {missing_values_after_removal}")

Number of missing values in  Label column after removal: 0

In [18]:
import numpy as np

## Check for Infinity or NaN values

In [19]:
print(df.isnull().sum())
print(df.isin([np.nan, np.inf, -np.inf]).sum())

 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64
 Destination Port              0
 Flow Duration                 0
 Total Fwd Packets             0
 Total Backward Packets        0
Total Length of Fwd Packets    0
                              ..
Idle Mean                      0
 Idle Std                      0
 Idle Max                      0
 Idle Min                      0
 Label                         0
Length: 79, dtype: int64

## Replace Infinity or Large Values

In [20]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)  # Replace NaN with a suitable value

In [21]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
count,74683.000000,7.468300e+04,74683.000000,74683.000000,74683.000000,7.468300e+04,74683.000000,74683.000000,74683.000000,74683.000000,...,74683.000000,7.468300e+04,7.468300e+04,7.468300e+04,7.468300e+04,7.468300e+04,7.468300e+04,7.468300e+04,7.468300e+04,74683.000000
mean,6598.408004,1.421755e+07,5.059612,4.977773,703.211186,6.592760e+03,362.194328,24.948663,115.547943,139.927645,...,21.946949,1.635603e+05,1.837720e+04,1.965434e+05,1.531283e+05,8.532105e+06,2.808235e+06,1.052080e+07,6.531823e+06,0.550219
std,16936.559792,2.831234e+07,15.929086,22.451737,3180.073318,3.982290e+04,1468.240437,146.191630,412.150018,627.634114,...,4.700861,8.460452e+05,2.888912e+05,1.008875e+06,8.215572e+05,1.848448e+07,1.026630e+07,2.252549e+07,1.678011e+07,0.497475
min,0.000000,0.000000e+00,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,80.000000,5.147550e+04,2.000000,1.000000,26.000000,0.000000e+00,6.000000,0.000000,6.000000,0.000000,...,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
50%,80.000000,1.108764e+06,3.000000,4.000000,30.000000,2.040000e+02,20.000000,0.000000,8.666667,3.464102,...,20.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000
75%,80.000000,8.013524e+06,5.000000,6.000000,64.000000,1.160100e+04,35.000000,6.000000,33.000000,10.263203,...,20.000000,1.014000e+03,0.000000e+00,1.014000e+03,1.013000e+03,7.902303e+06,0.000000e+00,7.912285e+06,6.733102e+06,1.000000
max,61538.000000,1.199994e+08,1681.000000,2942.000000,120783.000000,4.991419e+06,11680.000000,1472.000000,3867.000000,6692.644993,...,52.000000,1.000000e+08,3.950000e+07,1.000000e+08,1.000000e+08,1.200000e+08,6.530000e+07,1.200000e+08,1.200000e+08,1.000000

## Handle Missing Values:

In [22]:
label_column = df.iloc[:,-1:]
# df = df.dropna(subset=[label_column])

In [23]:
# Setup PyCaret
clf1 = setup(data=df, target=label_column, session_id=123)

## Compare models

In [ ]:
best_model = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .                14:30:41
Status     . . . . . . . . . . . . . . . . . .  Compiling Final Models
Estimator  . . . . . . . . . . . . . . . . . .    Ada Boost Classifier

Processing:   0%|          | 0/61 [00:00<?, ?it/s]

## Create a model

In [65]:
model = create_model('rf')  # Random Forest classifier

## Evaluate the model

In [85]:
evaluate_model(model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

# Make predictions on the entire dataset

In [73]:
!pip install tqdm

Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (4.66.1)

In [71]:
from tqdm import tqdm
from pycaret.classification import predict_model, setup

In [69]:
# Get the number of rows in your dataframe
num_rows = df.shape[0]

In [75]:
predictions = predict_model(model, data=df)

# Finalize the model

In [77]:
final_model = finalize_model(model)

# Save the model

In [80]:
save_model(final_model, 'final_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=[' Destination Port',
                                              ' Flow Duration',
                                              ' Total Fwd Packets',
                                              ' Total Backward Packets',
                                              'Total Length of Fwd Packets',
                                              ' Total Length of Bwd Packets',
                                              ' Fwd Packet Length Max',
                                              ' Fwd Packet Length Min',
                                              ' Fwd Packet Length Mean',
                                              ' Fwd Packet Length Std',
                                              'Bwd Packet Length Max',
                                              ' Bwd Packet L...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         n_estimators=100, n_jobs=-1,
                                         oob_score=False, random_state=123,
                                         verbose=0, warm_start=False))],
          verbose=False),
 'final_model.pkl')

# Load the saved model

In [81]:
loaded_model = load_model('final_model')

Transformation Pipeline and Model Successfully Loaded

<hr>